version: '3.9'

services:
  cassandra-db:
    image: cassandra:4

  queryer:
    image: nuvo/docker-cqlsh
    volumes:
      - ./data.cql:/scripts/data.cql
    environment:
      CQLSH_HOST: cassandra-db
      CQLSH_PORT: 9042
      CQLVERSION: 3.4.6
    depends_on:
      - cassandra-db
