version: '3.9'
services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test_db

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: don-sbn@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - db
